name: Databricks Repo Sync on Push
on: 
  push:
    branches: 
      - main 
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Executes repo sync
      uses: bkvarda/databricks-cli-github-action@main
      with:
        command: 'databricks repos update --repo-id 4122552516343800 --branch ${{ GITHUB_REF_NAME }}'
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

