# This is a basic workflow to help you get started with Actions

name: Databricks Repo Sync on Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Build image
      id: docker_build
      uses: docker/build-push-action@v2
      with: 
        push: false
        secrets: |
          "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}"
          "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}"
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    - name: Executes repo sync
      id: databricks_repo_sync
      uses: bkvarda/databricks-cli-github-action@main
      with:
        command: 'databricks repos list --debug'
