# This is a basic workflow to help you get started with Actions

name: Databricks Repo Sync on Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Executes repo sync
      uses: bkvarda/databricks-cli-github-action@main
      with:
        command: 'databricks'
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
